// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://owizlmihkzhenphfpmpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93aXpsbWloa3poZW5waGZwbXBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4MjgxNTUsImV4cCI6MjA1NTQwNDE1NX0.XllTzNSicqLmolIigCnMi-Sa64RntePDixZjohgh5gQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);